In [2]:
import matplotlib.pyplot as plt
import numpy as np

1번

In [10]:
sx=np.array([[0,1],[1,0]])
ex=np.linalg.eig(s_x)
print(ex)

(array([ 1., -1.]), array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))


In [11]:
sy=np.array([[0,-1j],[1j,0]])
ey=np.linalg.eig(s_y)
print(ey)

(array([ 1.+0.j, -1.+0.j]), array([[-0.        -0.70710678j,  0.70710678+0.j        ],
       [ 0.70710678+0.j        ,  0.        -0.70710678j]]))


In [12]:
sz=np.array([[1,0],[0,-1]])
ez=np.linalg.eig(s_z)
print(ez)

(array([ 1., -1.]), array([[1., 0.],
       [0., 1.]]))


2번

In [14]:
sx=np.array([[2,-1],[-1,2]])
ex=np.linalg.eig(sx)
print(ex)

(array([3., 1.]), array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]]))


eigenvalue에 의해서 w가 결정되고 eigenvector는 진폭을 의미한다.